"""
@project Reedo
@module 0001_initial
@author José Antonio Montaño (Lead Developer)
@inspired-by Alondra Gamino (Constant Inspiration)
@date 2026-05-21
"""
# Generated by Django 6.0.5 on 2026-05-21 22:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the book', max_length=255)),
                ('authors', models.JSONField(default=list, help_text='List of authors')),
                ('synopsis', models.TextField(blank=True, help_text='Synopsis of the book', null=True)),
                ('cover_image', models.URLField(blank=True, help_text='URL of the cover image', null=True)),
                ('genres', models.JSONField(default=list, help_text='List of genres')),
                ('total_pages', models.IntegerField(blank=True, help_text='Total pages of the book', null=True)),
                ('total_chapters', models.IntegerField(blank=True, help_text='Total chapters of the book', null=True)),
                ('published_date', models.DateField(blank=True, help_text='Date when book was published', null=True)),
                ('purchase_links', models.JSONField(blank=True, default=list, help_text='List of purchase links')),
                ('language', models.CharField(blank=True, help_text='Language of the book', max_length=50, null=True)),
                ('average_rating', models.FloatField(blank=True, help_text='Average rating of the book', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImmersionMode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration of the session in minutes', null=True)),
                ('session_type', models.CharField(choices=[('TIMED', 'Timed Session'), ('INFINITE', 'Infinite Stopwatch')], default='TIMED', help_text='Type of the session', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when session was created')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the library', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Description of the library', null=True)),
                ('primary_color', models.CharField(default='#000000', help_text='Primary color of the library', max_length=7)),
                ('is_public', models.BooleanField(default=True, help_text='Whether the library is public')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when library was created')),
                ('updated_at', models.DateField(auto_now=True, help_text='Date when library was updated')),
                ('user_id', models.ForeignKey(help_text='User to which this library belongs', on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Date when book was added to the library')),
                ('book_id', models.ForeignKey(help_text='Book to which this library book belongs', on_delete=django.db.models.deletion.CASCADE, related_name='library_books', to='books.books')),
                ('library_id', models.ForeignKey(help_text='Library to which this library book belongs', on_delete=django.db.models.deletion.CASCADE, related_name='library_books', to='books.library')),
            ],
            options={
                'unique_together': {('book_id', 'library_id')},
            },
        ),
        migrations.AddField(
            model_name='library',
            name='books',
            field=models.ManyToManyField(help_text='Books in the library', related_name='libraries', through='books.LibraryBook', to='books.books'),
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CURRENTLY_READING', 'Currently Reading'), ('READ_LATER', 'Read Later / Wishlist'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='READ_LATER', help_text='Status of the book for the user', max_length=20)),
                ('current_page', models.IntegerField(blank=True, help_text='Current page of the book', null=True)),
                ('progress_percentage', models.FloatField(blank=True, help_text='Progress percentage of the book', null=True)),
                ('is_primary_reading', models.BooleanField(default=False, help_text='Whether the book is the primary book being read')),
                ('honor_points', models.IntegerField(default=0, editable=False, help_text='Honor points earned for this book')),
                ('last_read_at', models.DateField(auto_now=True, help_text='Date when book was last read')),
                ('started_at', models.DateField(auto_now_add=True, help_text='Date when book was started')),
                ('finished_at', models.DateField(auto_now=True, help_text='Date when book was finished')),
                ('book_id', models.ForeignKey(help_text='Book to which this user belongs', on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to='books.books')),
                ('user_id', models.ForeignKey(help_text='User to which this book belongs', on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'book_id')},
            },
        ),
        migrations.CreateModel(
            name='ReadingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.IntegerField(blank=True, help_text='Page number of the note', null=True)),
                ('content', models.TextField(blank=True, help_text='Content of the note', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when note was created')),
                ('session', models.ForeignKey(help_text='Session to which this note belongs', on_delete=django.db.models.deletion.CASCADE, related_name='reading_notes', to='books.immersionmode')),
                ('user_book', models.ForeignKey(help_text='User book to which this note belongs', on_delete=django.db.models.deletion.CASCADE, related_name='reading_notes', to='books.userbook')),
            ],
        ),
        migrations.AddField(
            model_name='immersionmode',
            name='user_book',
            field=models.OneToOneField(help_text='User book to which this immersion mode belongs', on_delete=django.db.models.deletion.CASCADE, related_name='immersion_mode', to='books.userbook'),
        ),
    ]
