"""
@project Reedo
@module 0002_authors_genres_remove_books_authors_and_more
@author José Antonio Montaño (Lead Developer)
@inspired-by Alondra Gamino (Constant Inspiration)
@date 2026-05-27
"""
# Generated by Django 6.0.4 on 2026-05-26 01:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the author', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genre', models.CharField(help_text='Genre of the book', max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='books',
            name='genres',
        ),
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(help_text='Authors of the book', related_name='books', to='books.authors'),
        ),
        migrations.AddField(
            model_name='books',
            name='genres',
            field=models.ManyToManyField(help_text='Genres of the book', related_name='books', to='books.genres'),
        ),
    ]
