# Generated by Django 6.0.4 on 2026-06-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_authors_genres_remove_books_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='isbn',
            field=models.CharField(blank=True, help_text='ISBN-13 or ISBN-10 identifier', max_length=20, null=True, unique=True),
        ),
    ]
