# Generated by Django 6.0.4 on 2026-06-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(blank=True, help_text='ISBN-13 or ISBN-10 identifier', max_length=255, null=True, unique=True),
        ),
    ]
