# Generated by Django 6.0.4 on 2026-09-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='reading_time_seconds',
            field=models.IntegerField(default=0, help_text='Total reading time for this book in seconds'),
        ),
    ]
