"""
@project Reedo
@module 0001_initial
@author José Antonio Montaño (Lead Developer)
@inspired-by Alondra Gamino (Constant Inspiration)
@date 2026-05-21
"""
# Generated by Django 6.0.5 on 2026-05-21 22:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Echo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Text content of the echo')),
                ('is_spoiler', models.BooleanField(default=False, help_text='Whether the post contains spoilers')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the post was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the post was last updated')),
                ('shared_book', models.ForeignKey(blank=True, help_text='Book being shared in the echo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echoes', to='books.books')),
                ('user_id', models.ForeignKey(help_text='User who created the echo', on_delete=django.db.models.deletion.CASCADE, related_name='echoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Text content of the comment')),
                ('is_spoiler', models.BooleanField(default=False, help_text='Whether the comment contains spoilers')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the comment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the comment was last updated')),
                ('parent_comment_id', models.ForeignKey(blank=True, help_text='Parent comment to which this comment belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.comment')),
                ('user_id', models.ForeignKey(help_text='User who made the comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('echo_id', models.ForeignKey(help_text='Echo to which this comment belongs', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.echo')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Rating given by the user')),
                ('comment', models.TextField(help_text='Text content of the review')),
                ('is_spoiler', models.BooleanField(default=False, help_text='Whether the review contains spoilers')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the review was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the review was last updated')),
                ('book_id', models.ForeignKey(help_text='Book being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.books')),
                ('user_id', models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction', models.CharField(default='LIKE', help_text='Reaction made by the user', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the reaction was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the reaction was last updated')),
                ('comment_id', models.ForeignKey(help_text='Comment to which this reaction belongs', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.comment')),
                ('echo_id', models.ForeignKey(help_text='Echo to which this reaction belongs', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.echo')),
                ('user_id', models.ForeignKey(help_text='User who made the reaction', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
                ('review_id', models.ForeignKey(help_text='Review to which this reaction belongs', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.review')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='review_id',
            field=models.ForeignKey(help_text='Review to which this comment belongs', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.review'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the follow was created')),
                ('followed_id', models.ForeignKey(help_text='User who is being followed', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('follower_id', models.ForeignKey(help_text='User who is following', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower_id', 'followed_id')},
            },
        ),
    ]
