"""
@project Reedo
@module 0002_alter_reaction_comment_id_alter_reaction_echo_id_and_more
@author José Antonio Montaño (Lead Developer)
@inspired-by Alondra Gamino (Constant Inspiration)
@date 2026-08-25
"""
# Generated by Django 6.0.4 on 2026-08-23 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='comment_id',
            field=models.ForeignKey(blank=True, help_text='Comment to which this reaction belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.comment'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='echo_id',
            field=models.ForeignKey(blank=True, help_text='Echo to which this reaction belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.echo'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='review_id',
            field=models.ForeignKey(blank=True, help_text='Review to which this reaction belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.review'),
        ),
    ]
