"""
@project Reedo
@module 0003_alter_comment_echo_id_alter_comment_review_id
@author José Antonio Montaño (Lead Developer)
@inspired-by Alondra Gamino (Constant Inspiration)
@date 2026-08-25
"""
# Generated by Django 6.0.4 on 2026-08-23 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_reaction_comment_id_alter_reaction_echo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='echo_id',
            field=models.ForeignKey(blank=True, help_text='Echo to which this comment belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.echo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='review_id',
            field=models.ForeignKey(blank=True, help_text='Review to which this comment belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.review'),
        ),
    ]
