"""
@project Reedo
@module 0004_friendship
@author José Antonio Montaño (Lead Developer)
@inspired-by Alondra Gamino (Constant Inspiration)
@date 2026-08-25
"""
# Generated by Django 6.0.4 on 2026-08-26 01:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_comment_echo_id_alter_comment_review_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Status of the friendship request', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the request was sent')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the status was last updated')),
                ('receiver', models.ForeignKey(help_text='User who received the request', on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(help_text='User who sent the request', on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('requester', 'receiver')},
            },
        ),
    ]
