"""
@project Reedo
@module 0005_notification
@author José Antonio Montaño (Lead Developer)
@inspired-by Alondra Gamino (Constant Inspiration)
@date 2026-08-25
"""
# Generated by Django 6.0.4 on 2026-08-26 02:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_friendship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('FRIEND_REQUEST', 'Friend Request'), ('FRIEND_ACCEPT', 'Friend Request Accepted'), ('FRIEND_REJECT', 'Friend Request Rejected'), ('ECHO_LIKE', 'Echo Liked'), ('REVIEW_LIKE', 'Review Liked')], help_text='Type of notification', max_length=20)),
                ('message', models.CharField(help_text='Notification message content', max_length=255)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the notification was created')),
                ('echo', models.ForeignKey(blank=True, help_text='Linked Echo if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='social.echo')),
                ('friendship', models.ForeignKey(blank=True, help_text='Linked Friendship request if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='social.friendship')),
                ('recipient', models.ForeignKey(help_text='User receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(blank=True, help_text='Linked Review if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='social.review')),
                ('sender', models.ForeignKey(blank=True, help_text='User who triggered the notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
