# Generated by Django 6.0.5 on 2026-05-21 05:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=users.models.upload_thumbnail)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('city_residence', models.CharField(blank=True, max_length=150, null=True)),
                ('honor_points', models.IntegerField(default=0, editable=False, help_text='Total points for LeaderBoard ranking')),
                ('show_spoilers', models.BooleanField(default=True, help_text='Show spoilers in content recommendations')),
                ('member_since', models.DateField(auto_now_add=True, help_text='Date when user joined')),
                ('favorite_genres', models.JSONField(blank=True, default=list, help_text='List of favorite genres')),
                ('favorite_authors', models.JSONField(blank=True, default=list, help_text='List of favorite authors')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Badge name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the badge', null=True)),
                ('category', models.CharField(choices=[('STREAK', 'Streak-based'), ('OBJECTIVE', 'Objective-based'), ('SPECIAL', 'Special Event')], help_text='Category of the badge', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Badge image', null=True, upload_to='badges/')),
                ('icon', models.CharField(blank=True, help_text='Badge icon', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the badge is active')),
                ('earned_at', models.DateField(auto_now_add=True, help_text='Date when badge was earned')),
                ('user_id', models.ForeignKey(help_text='User to which this badge belongs', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.IntegerField(default=0, editable=False, help_text='Current consecutive days of activity')),
                ('best_streak', models.IntegerField(default=0, editable=False, help_text='Best streak achieved so far')),
                ('last_activity', models.DateField(auto_now_add=True, help_text='Last day of activity')),
                ('activate_at', models.DateField(editable=False, help_text='Is activated formally on the 3rd consecutive day of activity', null=True)),
                ('user_id', models.ForeignKey(help_text='User to which this streak belongs', on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the badge is active')),
                ('is_pinned_on_profile', models.BooleanField(default=False, help_text="Whether the badge is pinned on the user's profile")),
                ('earned_at', models.DateField(auto_now_add=True, help_text='Date when badge was earned')),
                ('badge_id', models.ForeignKey(help_text='Badge to which this user belongs', on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='users.badge')),
                ('user_id', models.ForeignKey(help_text='User to which this badge belongs', on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'badge_id')},
            },
        ),
    ]
