# Generated by Django 6.0.4 on 2026-05-26 01:06

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_authors_genres_remove_books_authors_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of the user', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Biography of the user', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Date of birth of the user', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_residence',
            field=models.CharField(blank=True, help_text='City of residence of the user', max_length=150, null=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_authors',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_genres',
        ),
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Profile picture of the user', null=True, upload_to=users.models.upload_thumbnail),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_authors',
            field=models.ManyToManyField(blank=True, help_text='Preferred authors for content recommendations', related_name='user_favorite_authors', to='books.authors'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, help_text='Preferred genres for content recommendations', related_name='user_favorite_genres', to='books.genres'),
        ),
    ]
