"""
@project Reedo
@module 0004_user_streak_days
@author José Antonio Montaño (Lead Developer)
@inspired-by Alondra Gamino (Constant Inspiration)
@date 2026-06-26
"""
# Generated by Django 6.0.4 on 2026-06-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='streak_days',
            field=models.IntegerField(default=0, help_text='Current consecutive days of activity'),
        ),
    ]
