# Generated by Django 6.0.4

from django.db import migrations

def make_fk_cascade(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        sql = """
        DO $$
        DECLARE
            r RECORD;
        BEGIN
            FOR r IN (
                SELECT 
                    tc.table_schema, 
                    tc.table_name, 
                    tc.constraint_name, 
                    kcu.column_name, 
                    ccu.table_schema AS foreign_table_schema, 
                    ccu.table_name AS foreign_table_name, 
                    ccu.column_name AS foreign_column_name 
                FROM 
                    information_schema.table_constraints AS tc 
                    JOIN information_schema.key_column_usage AS kcu
                      ON tc.constraint_name = kcu.constraint_name
                      AND tc.table_schema = kcu.table_schema
                    JOIN information_schema.constraint_column_usage AS ccu
                      ON ccu.constraint_name = tc.constraint_name
                      AND ccu.table_schema = tc.table_schema
                WHERE tc.constraint_type = 'FOREIGN KEY' 
                  AND ccu.table_name = 'users_user'
            ) LOOP
                EXECUTE 'ALTER TABLE ' || quote_ident(r.table_schema) || '.' || quote_ident(r.table_name) 
                    || ' DROP CONSTRAINT ' || quote_ident(r.constraint_name);
                EXECUTE 'ALTER TABLE ' || quote_ident(r.table_schema) || '.' || quote_ident(r.table_name) 
                    || ' ADD CONSTRAINT ' || quote_ident(r.constraint_name) 
                    || ' FOREIGN KEY (' || quote_ident(r.column_name) || ')'
                    || ' REFERENCES ' || quote_ident(r.foreign_table_schema) || '.' || quote_ident(r.foreign_table_name) 
                    || '(' || quote_ident(r.foreign_column_name) || ') ON DELETE CASCADE';
            END LOOP;
        END;
        $$;
        """
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(sql)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_streak_days'),
        ('books', '0004_alter_books_isbn'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_fk_cascade, reverse_code=migrations.RunPython.noop),
    ]
