# Generated by Django 6.0.4 on 2026-09-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cascade_user_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_reading_time_seconds',
            field=models.IntegerField(default=0, help_text='Total reading time in seconds'),
        ),
    ]
